version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      freera_net:
        ipv4_address: 213.18.0.10

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: 213.18.0.10
      REDIS_PORT: 6379
    networks:
      freera_net:
        ipv4_address: 213.18.0.20


networks:
    freera_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 213.18.0.0/16
